### ISSUE TITLE
"Connection reset error" when running apitest.py

### ISSUE THREAD

**Issue by asydney** [Azure/sonic-restapi#84]
Hi SONiC-RESTAPI folks,
                                         I was able to build both images. However, when I attempt to run "python apitest.py" on the container with the local image "rest-api-image-test_local:latest", the following error results:

...
ERROR: test_config_status_reset_get (__main__.ra_client_positive_tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
...

Can you kindly provide feedback?
-Syd

**Comment by asydney** [comment]
After further investigations with wireshark, it appears that only request with URI "http://localhost:8090/v1/config/restartdb"  was issued after running apitest.py. I logged onto the docker container (rest-api) and saw the following in /tmp/redis-out.log:

Creating Server TCP listening socket ::1:6379: bind: Cannot assign requested address

Google showed that this was a ipv6 error which was fixed with "sed -i "s/bind .*/bind 127.0.0.1/g" /etc/redis/redis.conf". After restarting the redis server, I re-run the python test and now see the following error:

ERROR: test_config_status_reset_get (__main__.ra_client_positive_tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/redis/connection.py", line 198, in _read_from_socket
    data = recv(self._sock, socket_read_size)
  File "/usr/local/lib/python3.8/dist-packages/redis/_compat.py", line 72, in recv
    return sock.recv(*args, **kwargs)
ConnectionResetError: [Errno 104] Connection reset by peer

I'm not quite sure what this means, but perhaps there are some compatibility issues? 

I should mention that when building the docker images, copy.sh referenced old libraries (e.g. libhiredis0.13_0.13.3-2_amd64.deb) while the repository at https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/buildimage-vs-all/lastSuccessfulBuild/artifact/target/debs/*zip*/debs.zip had newer versions (e.g. libhiredis0.14_0.14.0-3~bpo9+1_amd64.deb). 

This resulted in several issues while using "stretch" as the base image in the docker file, so upgraded to "buster". With a few more tweaks, I was able to build the image, but maybe this is the source of theses issues. 

In any case, can you kindly either a) provide the old libraries such that we can rebuild with stretch or b) provide updated instructions (i.e. copy.sh, Dockerfile etc..) that match with the new libraries?

**Comment by asydney** [comment]
BTW. I should mention that my objective for using the "rest-api" container, is that I will somehow be able to push CLI commands (e.g. "show version"), remotely to the switch via REST: Below is an example of pushing "show version" to a switch running on IP 192.168.1.5 with a REST server listening on port 80 and the endpoint "command-api":

remote_host>curl --insecure -u admin -H "Content-Type: application/json" -X POST -d '{"jsonrpc":"2.0", "method":"runCmds", "params":{ "version":1, "cmds":["show version"], "format":"json"}, "id":""}' http:///192.168.1.5:80/command-api | json_reformat

If you can recall, I asked this question recently "How do we push CLI commands to SONiC switches via REST?", but it was transferred to the Azure/sonic-mgmt-framework project. If I will not be able to execute CLI commands using these containers, please let me know.
